// Explicit retry: a new Run for the same frozen input (T1.02.b, §27.2.7).
//
// §27.2.7: "Task.failed 表示当前执行失败，可由显式 retry 命令 CAS 到 queued 并
// 关联新的 Run；不能让旧 Run 从 failed 回 running。重试使用原输入快照。" A retry
// is therefore two facts in one transaction:
//
//   - a *new* Run (new id, new identity, status queued, revision 1,
//     retry_of_run_id pointing at the old one) that copies the frozen input pin
//     of the old Run verbatim — same task, project, binding and binding
//     revision, base manifest hash, base commit, agent revision, input snapshot
//     id and hash, and budget. Nothing about the old Run is read back into the
//     new one except those pins: the new Run is a new execution of the same
//     frozen input, not a continuation of the old one.
//   - the Task CASed from failed to queued.
//
// The old Run and its events are not touched at all: §27.2.1 "重试创建新 Run，旧
// events、usage、approvals 保留". Its status stays failed (terminal), its revision
// does not move, and no event is appended to its timeline. That is what makes "the
// old Run cannot go from failed back to running" a structural property rather
// than a rule someone has to remember: nothing in this file writes to the old
// run row.
//
// Two things this file deliberately does not create:
//
//   - A "run created" event. The closed execution-event enum (§27.4, CA-1/CA-2)
//     has no run.created/run.queued type, and inventing one would be a contract
//     change of its own. The new Run's timeline therefore starts with its first
//     transition (scheduler.claimed, the queued→starting row), which is the same
//     shape a first-try Run has: a queued Run has no event until it is claimed.
//     T1.04 (the command service) may want a creation event for the client's
//     command ledger; that is a decision for its card, not a type to invent here.
//   - A copy of the old Run's approvals. The approvals table does not exist yet
//     (T2.02 creates it), so there is nothing to copy today — and when it does
//     exist, the rule is that a retry must *not* copy them: §27.2.3 binds an
//     approval to a subject, a normalised parameter hash, the base manifest
//     hash, the policy version and the agent revision, so a grant made for the
//     failed attempt is not a grant for a new Run. T2.02 owns making that true;
//     this file only refuses to carry anything approval-shaped forward.

package runstore

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/codeflow/backend/internal/run"
)

// RetryInput is one explicit retry request: which failed run to retry, under
// which new identity, against which task revision.
type RetryInput struct {
	// OriginalRunID is the Run to retry. Required; it must exist and have ended
	// without completing (failed, cancelled or expired). Whether a retry is
	// allowed at all is the task's decision (§27.2.7: only a failed task is
	// requeued), see RetryRunTx.
	OriginalRunID string
	// NewRunID is the new Run's id. Required and generated by the caller (a
	// UUID), not derived from the old id: the new Run is a new identity, and
	// deriving one from the other would let a client predict it and would make
	// "new Run" and "same Run" indistinguishable in a log. The store refuses an
	// id that already exists.
	NewRunID string
	// ExpectedTaskRevision is the task revision the caller read. Required,
	// >= 1: the retry CASes the task, so a concurrent change to the task is a
	// conflict rather than a lost update.
	ExpectedTaskRevision int64
	// At is when the retry happened. Required (non-zero); it is the new Run's
	// created_at and updated_at and the task's updated_at.
	At time.Time
	// CommandID is the idempotency command that requested the retry, stored on
	// the new Run. Optional (nil for a system-initiated retry); runs.command_id
	// is UNIQUE when set, so reusing one is refused by the database.
	CommandID *string
}

// RetryResult is the outcome of an accepted retry: the new Run as stored and
// the Task after its CAS.
type RetryResult struct {
	Run  run.Run
	Task run.Task
}

// RetryRunTx creates the new Run of an explicit retry and CASes its task from
// failed to queued, inside the caller's transaction.
//
// It never opens a transaction of its own: the new Run and the task CAS must
// commit or roll back together, or the store could leave a queued Run for a task
// that is still failed (or a queued task with no Run to execute). The caller owns
// the transaction (Store.WithTx).
//
// Validation, all of it before any SQL runs except where noted, so a rejected
// call leaves the caller's transaction untouched:
//
//   - OriginalRunID, NewRunID and At are required, ExpectedTaskRevision >= 1,
//     and NewRunID must differ from OriginalRunID. Violations wrap
//     ErrInvalidTransitionInput.
//   - The original Run must exist (ErrNotFound) and have ended without
//     completing: failed, cancelled or expired. A running (or otherwise
//     non-terminal) original run is ErrRunNotRetryable — §27.2.7 will not fork a
//     second execution off a live one — and so is a completed one, whose output
//     is reviewed or merged rather than re-executed. Cancelled and expired runs
//     are not refused here: a retry never reopens them (it creates a new Run),
//     and whether the work may be requeued is decided by the task below. A hard
//     deadline that expired a run whose task was then failed is exactly the case
//     an explicit retry exists for; a user cancel that also cancelled the task is
//     refused by the task rule.
//   - Its task must be failed (ErrTaskNotRetryable otherwise). This is the
//     §27.2.7 rule that completed/cancelled tasks are not reopened.
//   - The task must have no other non-terminal Run (ErrActiveRunExists): §19.1
//     allows at most one active Run per task, and the partial unique index
//     idx_runs_one_active_per_task enforces it behind this check.
//   - The task CAS must match ExpectedTaskRevision, or the caller gets
//     *TaskRevisionConflictError (which is also ErrRevisionConflict).
//
// The order of the checks is deliberate: the cheap "is this run even retryable"
// judgements come before the task's, so a caller retrying a running run hears
// that instead of a task-status complaint about a task that is still running.
func RetryRunTx(ctx context.Context, tx Tx, in RetryInput) (RetryResult, error) {
	if tx == nil {
		return RetryResult{}, fmt.Errorf("%w: nil Tx", ErrInvalidTransitionInput)
	}
	if err := validateRetryInput(in); err != nil {
		return RetryResult{}, err
	}

	original, err := GetRun(ctx, tx, in.OriginalRunID)
	if err != nil {
		return RetryResult{}, fmt.Errorf("retry run %s: %w", in.OriginalRunID, err)
	}
	if !original.Status.IsTerminal() || original.Status == run.RunStatusCompleted {
		return RetryResult{}, fmt.Errorf("%w: run %s is %s (a retry needs a run that ended without completing; "+
			"a completed run is reviewed or merged, and a live run is cancelled first)",
			ErrRunNotRetryable, in.OriginalRunID, original.Status)
	}

	task, err := GetTask(ctx, tx, original.TaskID)
	if err != nil {
		return RetryResult{}, fmt.Errorf("retry run %s: %w", in.OriginalRunID, err)
	}
	if task.Status != run.TaskStatusFailed {
		return RetryResult{}, fmt.Errorf("%w: task %s is %s, not failed (completed and cancelled tasks are not reopened)",
			ErrTaskNotRetryable, task.ID, task.Status)
	}

	// §19.1: one active Run per task. The original run is terminal, so it is not
	// the conflict; any other non-terminal run of this task is. The check is
	// inside the caller's transaction and the database's partial unique index
	// backs it up, so a concurrent creator cannot slip past it.
	if err := checkNoActiveRunForTask(ctx, tx, task.ID, in.NewRunID); err != nil {
		return RetryResult{}, err
	}

	// The new Run reuses the original's frozen input pin and nothing else: the
	// input snapshot is the one §27.2.7 requires a retry to use, and the binding
	// revision, base manifest and agent revision are part of what that execution
	// was frozen against. Copying them is not "carrying state forward" — it is
	// the same frozen input, executed again under a new identity.
	newRun := run.Run{
		ID:               in.NewRunID,
		TaskID:           original.TaskID,
		ProjectID:        original.ProjectID,
		CommandID:        in.CommandID,
		BindingID:        original.BindingID,
		BindingRevision:  original.BindingRevision,
		BaseManifestHash: original.BaseManifestHash,
		BaseCommit:       original.BaseCommit,
		AgentRevisionID:  original.AgentRevisionID,
		InputSnapshotID:  original.InputSnapshotID,
		// InputSnapshotHash is recomputed by the database trigger's check against
		// the snapshot row, but the column is written from here, so it must be the
		// original's hash: a retry of a retry still pins the first snapshot.
		InputSnapshotHash: original.InputSnapshotHash,
		Budget:            original.Budget,
		Status:            run.RunStatusQueued,
		RetryOfRunID:      stringPtrCopy(original.ID),
		CreatedAt:         in.At,
		UpdatedAt:         in.At,
	}
	// InsertRun forces revision 1 and refuses any status but queued, so the
	// "new identity" shape of §15 T1.02 is enforced by the store rather than by
	// this function's struct literal.
	if err := InsertRun(ctx, tx, &newRun); err != nil {
		return RetryResult{}, fmt.Errorf("retry run %s: %w", in.OriginalRunID, err)
	}

	queuedTask, err := UpdateTaskStatusCAS(ctx, tx, task.ID, in.ExpectedTaskRevision, run.TaskStatusQueued, in.At)
	if err != nil {
		return RetryResult{}, fmt.Errorf("retry run %s: %w", in.OriginalRunID, err)
	}

	return RetryResult{Run: newRun, Task: queuedTask}, nil
}

// validateRetryInput enforces the retry contract before any SQL runs.
func validateRetryInput(in RetryInput) error {
	if strings.TrimSpace(in.OriginalRunID) == "" {
		return fmt.Errorf("%w: OriginalRunID is empty", ErrInvalidTransitionInput)
	}
	if strings.TrimSpace(in.NewRunID) == "" {
		return fmt.Errorf("%w: NewRunID is empty", ErrInvalidTransitionInput)
	}
	if in.NewRunID == in.OriginalRunID {
		return fmt.Errorf("%w: NewRunID equals OriginalRunID (%s); a retry creates a new run",
			ErrInvalidTransitionInput, in.NewRunID)
	}
	if in.ExpectedTaskRevision < 1 {
		return fmt.Errorf("%w: ExpectedTaskRevision %d must be >= 1",
			ErrInvalidTransitionInput, in.ExpectedTaskRevision)
	}
	if in.At.IsZero() {
		return fmt.Errorf("%w: At is zero", ErrInvalidTransitionInput)
	}
	return checkOptionalTransitionID("CommandID", in.CommandID)
}

// checkNoActiveRunForTask refuses a retry whose task already has a non-terminal
// run other than the one being replaced.
//
// The scan is deliberately over ListRunsByTask rather than a bespoke COUNT: the
// read is the one the store already exposes, and "which runs does this task
// have" is exactly the question. A run that is not terminal is active by
// definition (§21.1: only completed/failed/cancelled/expired are terminal).
func checkNoActiveRunForTask(ctx context.Context, tx Tx, taskID, newRunID string) error {
	runs, err := ListRunsByTask(ctx, tx, taskID)
	if err != nil {
		return fmt.Errorf("check active runs of task %s: %w", taskID, err)
	}
	for _, r := range runs {
		if r.Status.IsTerminal() {
			continue
		}
		return fmt.Errorf("%w: task %s already has run %s in status %s (at most one active run per task)",
			ErrActiveRunExists, taskID, r.ID, r.Status)
	}
	// The new id must be free. InsertRun would report the primary-key refusal
	// anyway, but a caller that reuses an id it has already used deserves a
	// message that says so; this check is a read inside the same transaction, so
	// it cannot race with itself, and the index remains the arbiter.
	if _, err := GetRun(ctx, tx, newRunID); err == nil {
		return fmt.Errorf("%w: run %s already exists", ErrInvalidTransitionInput, newRunID)
	} else if !errors.Is(err, ErrNotFound) {
		return fmt.Errorf("check run %s: %w", newRunID, err)
	}
	return nil
}
